apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: test-quiz
  ports:
  - port: 61111        # Порт сервиса
    targetPort: 8080   # Порт контейнера
  type: ClusterIP